## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
n = input()
x = np.arange(0, int(n)+1) # создаем одномерный массив
x_list = list(x) # делаем списком
x_list.reverse() # к списку применяем метод reverse
np.array(x_list) # делаем одномерным массивом

6


array([6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
## Из равномерно распределенных внутри N до 0

n = input()
x = np.linspace(int(n), 0, int(n)) # создали матрицу методом linspace. 1-й элемент = n, в linspace работает
x1=np.diag(x) # преобразовали ее в диагональную матрицу размерностью n*n
x1

6


array([[6. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 4.8, 0. , 0. , 0. , 0. ],
       [0. , 0. , 3.6, 0. , 0. , 0. ],
       [0. , 0. , 0. , 2.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ]])

In [4]:
# Из целочисленных элементов от N до 0

n = input()
x = np.arange(0, int(n)+1) # создаем одномерный массив
x_list = list(x) # делаем списком
x_list.reverse() # к списку применяем метод reverse
x2 = np.diag(np.array(x_list)) # делаем диагональной матрицей
x2

6


array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [5]:
def summa_diag(array_d):
    '''
    считаем сумму диагональных элементов
    '''
    total_sum = 0
    n = array_d[0, 0]  
    for i in range(0, int(n)):
        total_sum += array_d[i, i]
    
    print(total_sum)

In [6]:
summa_diag(x1)

18.0


In [7]:
summa_diag(x2)

21


## Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

Взяла датасет ml-latest-small

In [35]:
import pandas as pd

In [36]:
ratings = pd.read_csv('ratings.csv')

In [37]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [39]:
# выгрузили таблицу movies, так как там есть названия фильмов
movies = pd.read_csv('movies.csv')
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [46]:
# добавили к ratings данные из movies 
r_m = ratings.merge(movies, on='movieId', how='left')
r_m.head(1)

userId  movieId  rating  timestamp             title  \
0       1        1     4.0  964982703  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy

In [52]:
# создали датасет только с оценками 5.0
ratings_5 = r_m[r_m.rating == 5.0]

# посчитали кол-во входов по полю title
ratings_5['title'].value_counts().head()

Shawshank Redemption, The (1994)             153
Pulp Fiction (1994)                          123
Forrest Gump (1994)                          116
Matrix, The (1999)                           109
Star Wars: Episode IV - A New Hope (1977)    104
Name: title, dtype: int64

## Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [13]:
power = pd.read_csv('power.csv')

In [14]:
power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [15]:
# отфильтровали по странам
filtered_c = power[ (power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country'] == 'Estonia')]

# отфильтровали по категориям
filtered_c_c = filtered_c[(filtered_c['category'] == 4) | (filtered_c['category'] == 12)| (filtered_c['category'] == 21)]

# отфитровали по годам
filtered_c_c_y = filtered_c_c[(filtered_c_c['year'] == 2005)|
                             (filtered_c_c['year'] == 2006)|
                             (filtered_c_c['year'] == 2007)|
                             (filtered_c_c['year'] == 2008)|
                             (filtered_c_c['year'] == 2009)|
                             (filtered_c_c['year'] == 2010)]

# оставили только положительные значения
filtered_c_c_y_p = filtered_c_c_y[filtered_c_c_y.quantity > 0]

# посчитали сумму по столбцу quantity
sum_quantity = filtered_c_c_y_p['quantity'].sum()
sum_quantity

240580.0

## Задание 5

Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [16]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [17]:
from numpy import linalg

In [18]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True